services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cubecrit
      - POSTGRES_USER=cubecrit
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  db-test:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432

  